### ISSUE TITLE
nice module

### ISSUE THREAD

**Issue by sunnysideup** [lekoala/silverstripe-starter-theme#1]
This looks really interesting.

Do you have any screenshots of what it looks like?

What do you recommend for compiling (e.g. webpack) - is there a specific reason you did not include this?

**Comment by lekoala** [comment]
@sunnysideup hey thanks. I don't have a project running this at the moment it was more an experiment. but it should be easy enough to give it a try on a fresh install

i'm compiling files directly in vscode, but if anything, i'm now using esbuild + dart sass as my go to build tools and if I had to update the theme, that's probably what I would do

**Comment by lekoala** [comment]
@sunnysideup hey actually good thing you reminded me of the existence of this module, starting a new website today and I gave this a bit of a 2022 refresh :-) with build tools for example and bootstrap 5.2

regarding your question about screenshot, it doesn't look like anything, just a plain header/footer, the goal is not to provide a default visual style, but a development starting point
